### ISSUE TITLE
NuGet package dependencies overly restrictive

### ISSUE THREAD

**Issue by tdgrunenwald** [derek-will/CrcSharp#4]
The NuGet package lists .net5.0 as a dependency, however the library can be built against many other versions of .NET such as .NET Framework (e.g. v4.7, etc.).

The dependency list should be updated for broader support.

**Comment by derek-will** [comment]
Hi @tdgrunenwald, thanks for raising this issue. It was a definite oversight of mine when migrating the project over. 

I changed the build targets from **.NET 5** to **.NET Standard 2.0, .NET Frameworks 4.0, 4.5, 4.6.1**. The change will result in much wider coverage of .NET frameworks and versions.

With a minor change, pre-.NET 4.0 Frameworks can be supported by removing a single LINQ dependency. I won't offer such builds until someone requests it. .NET Framework 4.0 is pretty ancient at this point so that _should_ be good enough, but I am definitely open to supporting older frameworks if requested here.

**Comment by tdgrunenwald** [comment]
Great! Thanks for the update
